// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZv7uPmxfWHztTnSmjZX10zR8IiZb48qc',
    appId: '1:398255490644:web:340c51f206f5a309a24fc1',
    messagingSenderId: '398255490644',
    projectId: 'demoauthen-d01ba',
    authDomain: 'demoauthen-d01ba.firebaseapp.com',
    storageBucket: 'demoauthen-d01ba.firebasestorage.app',
    measurementId: 'G-HBJGH45K2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6y04Bm0pVOS3TPo_Nb7fvLAzrbOun1_o',
    appId: '1:398255490644:android:d397887f42b20a23a24fc1',
    messagingSenderId: '398255490644',
    projectId: 'demoauthen-d01ba',
    storageBucket: 'demoauthen-d01ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnU_b-4neQIr7H-CbLUBNfFk6enSjyKd8',
    appId: '1:398255490644:ios:f5fa7fbf1b2d43a8a24fc1',
    messagingSenderId: '398255490644',
    projectId: 'demoauthen-d01ba',
    storageBucket: 'demoauthen-d01ba.firebasestorage.app',
    iosBundleId: 'com.example.vattunongnghiepApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnU_b-4neQIr7H-CbLUBNfFk6enSjyKd8',
    appId: '1:398255490644:ios:f5fa7fbf1b2d43a8a24fc1',
    messagingSenderId: '398255490644',
    projectId: 'demoauthen-d01ba',
    storageBucket: 'demoauthen-d01ba.firebasestorage.app',
    iosBundleId: 'com.example.vattunongnghiepApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZv7uPmxfWHztTnSmjZX10zR8IiZb48qc',
    appId: '1:398255490644:web:52b7d802a144a28ba24fc1',
    messagingSenderId: '398255490644',
    projectId: 'demoauthen-d01ba',
    authDomain: 'demoauthen-d01ba.firebaseapp.com',
    storageBucket: 'demoauthen-d01ba.firebasestorage.app',
    measurementId: 'G-7W8HGY53M0',
  );
}
